apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2024-06-05T11:13:25Z"
  generation: 3
  name: new-replica-set
  namespace: default
  resourceVersion: "1383"
  uid: bd36881b-99db-4433-ba87-c872f598290e
spec:
  replicas: 5
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: busybox-pod
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo Hello Kubernetes! && sleep 3600
        image: busybox
        imagePullPolicy: Always
        name: busybox-container
        resources: {}